spring:
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    drop-first: false

jwt:
  expiration-minutes: 15
nginx:
  require-proxy: true
  trustedIps:
    - "178.156.204.95"
    - "152.167.110.92"
    - "127.0.0.1"
    - "::1"
    - "172.17.0.0/16"
    - "10.0.0.5/32"

rosafiesta:
  web-socket:
    allowedOrigins:
      - "http://localhost:8080"
      - "http://rosafiesta.strangled.net"
  email:
    url: "https://rosafiesta.com"
  ip:
    rate-limit:
      apply-limit: true